### ISSUE TITLE
Tracking: customization requests from dartdoc tool

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#1019]
- [ ] run `dartdoc` from Dart code (https://github.com/dart-lang/dartdoc/issues/1609) (importing as a library)
- [ ] custom path for static assets (so we don't need to store it for each package version separately)
- [ ] customization of `<header>` and `breadcrumbs`

**Comment by isoos** [comment]
@jcollins-g: these are the currently known ones. We plan to do further integration within the pub site, and that may require a different design, so I'd rather postpone the `<header>` and `breadcrumbs` parts for now.

**Comment by jcollins-g** [comment]
Does the --header command-line option not provide sufficient customization for the header?

The static assets request could probably be filed as its own issue.  I welcome feature requests on dart-lang/dartdoc.

**Comment by kevmoo** [comment]
> custom path for static assets (so we don't need to store it for each package version separately)

You likely want to have one copy for each version of dartdoc – in case the set of expected assets evolves from version to version

**Comment by isoos** [comment]
`--header` puts extra content inside the `<head>` element (at the end of it). We want to customize (and override) the breadcrumbs with an extra logo and a link to the package page on pub (instead of the package homepage).

**Comment by isoos** [comment]
>> custom path for static assets (so we don't need to store it for each package version separately)

> You likely want to have one copy for each version of dartdoc – in case the set of expected assets evolves from version to version

Yes, but storing one copy is still better than `count(PVs)` copy :)

**Comment by jcollins-g** [comment]
Re: header, OK, that makes sense.  That belongs in it's own dartdoc issue too.

**Comment by isoos** [comment]
These issues are either resolved or a good workaround exists.
