### ISSUE TITLE
Status tracker for pub refresh features

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#154]
Analyzer:
- [x] identify package environment (e.g. console, browser, mobile, all-around)
- [x] analyze potential package resolution issues:
  - [x] detect use of `any` (https://github.com/dart-lang/pana/issues/68)
  - [x] too broad version range (may cause a incompatibility https://github.com/dart-lang/pana/issues/69)
  - [x] too narrow version range (is not able to resolve versions https://github.com/dart-lang/pana/issues/70) 
  - [x] outdated (has newer dependencies)
  - [x] handle `pub get` with `sdk: flutter` (use the latest Flutter SDK for analysis?)
- [x] track license
  - [x] mark if missing
  - [x] recognize popular ones
- [ ] test
  - [ ] tests are running and passing (requires hardened run environment)
  - [ ] test code coverage %
- [ ] documentation coverage

Analyzer pipeline:
- [x] trigger analysis on new version upload
- [x] trigger analysis on most recent version (dev and stable) when a dependency is updated (https://github.com/dart-lang/pub-dartlang-dart/issues/317)
- [x] trigger analysis on most recent version (dev and stable) when a last analysis is too old
- [x] trigger analysis on older versions (when idle)
- [x] handle analysis request, run analyzer, store results

Search for packages with filters per environment:
- [x] identify environment and store in Datastore
- [x] show environment icon on package page, package listing and search results
- [x] update index on search backend
- [x] search filter (URL parsing, forwarding to search backend)
- [ ] search UI (dropdown or other input)

Rank popular packages:
- [x] get usage stats and store in Datastore, normalize popularity metric
- [x] show popularity info on package page, package listing and search results
- [x] update index on search backend
- [x] search filter/order (URL parsing, forwarding to search backend)
- [ ] search UI (toggle between popular or recently updated)
- [x] homepage shows top 10 popular packages

Package health:
- [ ] new pubspec metadata to mark package as deprecated
- [ ] new pubspec metadata for issue tracker URL
- [x] track analyzer status and store in Datastore (analyzer clean, strong mode clean, deprecated, ...)
- [ ] show health info on package page, package listing and search results
- [x] update index on search backend
- [x] search filter (URL parsing, forwarding to search backend)
- [ ] search UI (checkbox or other input)

Support more Flutter:
- [x] ~~identify Flutter plugins,~~
- [x] ~~show icon on package page, package listing and search results~~
- [x] ~~update index on search backend~~
- [x] ~~search filter (URL parsing, forwarding to search backend)~~
- [ ] search UI (dropdown or other input)

**Comment by isoos** [comment]
/cc @kevmoo @mkustermann @filiph 
I've started to track the major items here, mostly backend, some lower-priority.

**Comment by isoos** [comment]
I got most of it from the PRD, nevertheless, it would be worth if somebody else would go through it and double-check if none is missing.

**Comment by isoos** [comment]
Closing this, as the pending items on this list are either under discussion, or obsolete, or we have a tracking issue.
