### ISSUE TITLE
New design's WIP tracking  

### ISSUE THREAD

**Issue by isoos** [dart-lang/pub-dartlang-dart#391]
- [x] global CSS
  - [x] scoped rules (markdown content with lists)
  - [x] '-home' should not be on `main`, instead on level down (simpler templates)
  - [x] remove 'body#id' (simpler templates)
- [ ] Home page
  - [ ] platforms links: exclusive or filter-only?
  - [x] newest packages
  - [x] popular packages
  - [x] column widths to be equal
- [ ] Search's platform links
  - [ ] Home page -> platform filter -> "All" has empty results
- [ ] List pages
  - [ ] title and description looks weird
  - [x] pagination design
- [x] Package page
  - [x] design for "Versions" tab and the versions page
  - [x] proper scrolling with in-page anchor links
  - [x] side box word wrap
  - [x] score box -> analysis results
  - [x] installing tab misses styles?
